# Configuration for the pathway prediction pipeline

[database]
# Path to the DIAMOND database file for sequence alignment.
path = "./pathway/database/IAA_database_complete.dmnd"

[criteria]
# Criteria for selecting the best BLAST hit for each query sequence.
# Available options: score (bit-score), evalue, identity, coverage.
column = "score" # (default: score)

# Filters to apply to the BLAST hits.
# Available options: score (bit-score), evalue, identity, coverage.
filter = [
    "coverage=50",
]

[match_enzyme]
# Model to use for calculating the existence score of enzymes and compounds.
# Available options: "logistic", "binary"
model = "logistic"

[executable]
# Paths to the required external executable files.
# These can be absolute paths or relative to the location of this config file.
prodigal_path = "./bin/prodigal" # Path to the Prodigal executable for gene prediction.
diamond_path = "./bin/diamond"   # Path to the DIAMOND executable for protein alignment.
