[database]
path = "./pathway/database/IAA_database_complete.dmnd"

[criteria]
column = "score" # best hit criteria (default: score)
filter = [
    "coverage=50",
] # options: score (bit-score), evalue, identity (%), coverage (query coverage, %)

[match_enzyme]
model = "logistic" # "logistic" or "binary"

[executable]
prodigal_path = "./bin/prodigal" # download "prodigal" and put its path here
diamond_path = "./bin/diamond"   # download "diamond" and put its path here
