[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
include = ["biopathpred*"]

[project]
name = "biopathpred"
version = "0.0.1"
authors = [
  { name = "Zheng-Xiang Ye", email="b07613010@ntu.edu.tw"},
  { name="Steven Wu", email="stevenwu@ntu.edu.tw" },
]
description = "A Probabilistic Approach for Predicting Indole-3-Acetic Acid Synthesis in Bacteria Using Genomic Data"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
  "tqdm",
  "biopython",
  "numpy>=1.23.5,<2.0.0",
  "pandas>=1.5.2,<2.0.0",
  "tomli>=2.0.1"
]

[tool.pytest.ini_options]
testpaths = ["tests"]


[project.optional-dependencies]
test = [
  "pytest>=7.1.2",
]

[project.scripts]
biopathpred = "biopathpred.cli:main"
